name: main

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
          #- macos-10.15
          - windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          install-deps: 'true'

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Upload build artifacts (Vuk binary)
        if: matrix.os != 'windows-latest'
        uses: actions/upload-artifact@v1
        with:
          name: vuk-bin
          path: target/release/vuk

      - name: Upload build artifacts (Vuk binary, Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v1
        with:
          name: vuk-bin
          path: target/release/vuk.exe

      - name: Upload build artifacts (Qt library)
        uses: actions/upload-artifact@v1
        with:
          name: qt-lib
          path: ${{ runner.workspace }}/Qt

