name: main

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
          #- macos-10.15
          - windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - name: Set SHORT_SHA env
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ${{ runner.workspace }}/Qt
          key: ${{ runner.os }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          install-deps: 'true'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v1

      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Prepare package (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir -p ~/pkg/vuk-$SHORT_SHA
          cp target/release/vuk.exe ~/pkg/vuk-$SHORT_SHA
          cp -r $QT_PLUGIN_PATH ~/pkg/vuk-$SHORT_SHA
          cp -r $QML2_IMPORT_PATH ~/pkg/vuk-$SHORT_SHA
          cp $Qt5_Dir/bin/*.dll ~/pkg/vuk-$SHORT_SHA
          rm -f ~/pkg/vuk-$SHORT_SHA/*d.dll
          rm -rf ~/pkg/vuk-$SHORT_SHA/plugins/geoservices
          rm -rf ~/pkg/vuk-$SHORT_SHA/plugins/sqldrivers

      - name: Prepare package (Linux)
        if: matrix.os != 'windows-latest'
        run: |
          mkdir -p ~/pkg/vuk-$SHORT_SHA
          cp target/release/vuk ~/pkg/vuk-$SHORT_SHA

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: vuk-pkg
          path: '~/pkg'

